/*
Copyright (c) 2010, Mickaël Delahaye <mickael.delahaye@gmail.com>

Permission to use, copy, modify, and/or distribute this software for any purpose
with or without fee is hereby granted, provided that the above copyright notice
and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED “AS IS” AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
THIS SOFTWARE.
*/

typedef [abstract, finalize(yicesl_del_context)] void * context;
typedef [abstract, errorcode, errorcheck(checkerror)] int error_code;

[mlname(set_verbosity)]
void yicesl_set_verbosity(int l);

[mlname(version), string]
char * yicesl_version();

[mlname(enable_type_checker)]
void yicesl_enable_type_checker(boolean flag);

[mlname(enable_log_file)]
void yicesl_enable_log_file([string] char * file_name);

[mlname(mk_context)]
context yicesl_mk_context();

//void yicesl_del_context(context ctx);
// -> Used as the context type finalize

[mlname(read)]
error_code yicesl_read(context ctx,[string] char * cmd) ;

[mlname(inconsitent)]
boolean yicesl_inconsistent(context ctx);

//char * yicesl_get_last_error_message();
// -> Used in the error check of error_code

[mlname(set_output_file)]
void yicesl_set_output_file([string] char * file_name);
